### ISSUE TITLE
Mismatch between roll number and station

### ISSUE THREAD

**Issue by low-decarie** [asc-csa/Alouette_extract#2]
Roll number may be expected to be matched with a single station, however, some rolls have a few ionogrammes being matched to another station.

Error rate seems to increase with increasing ionogramme number within a roll, potentially hinting to a cumulative misalignment of the grid.

Issue identified by: -----

**Comment by emilinecsa** [comment]
What if we apply the first valid station number parsed to all the ionograms of the roll?

**Comment by emilinecsa** [comment]
I got a confirmation that this issue is fixed. So I close it.
