### ISSUE TITLE
Mismatch between station number and station location likely due to time period

### ISSUE THREAD

**Issue by low-decarie** [asc-csa/Alouette_extract#3]
Some rolls contain ionogrammes with the same station numeric code being recognized, but being assigned to different stations, maybe due to the piecemeal adoption of these station code changes (e.g. stations would not change their code mid-roll). 

Issue identified by: -----

**Comment by RoksanaSheikholmolouki** [comment]
According to the supporting documentation, the station numbers of some satellites changed throughout the years. For example, Chile had two station number changes in 1963 or Winfield England had three changes. More information can be found [here.](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fdonnees-data.asc-csa.gc.ca%2Fusers%2FOpenData_DonneesOuvertes%2Fpub%2FAlouetteData%2FData%2520specifications%2520Alouette-I%2520.docx&wdOrigin=BROWSELINK)

**Issue**:  These changes occurred at specific time of the month but there are no information (or at least on the document above) on the metadata regarding the month the ionograms were captured. The available categories are “Year”, “Day”, “Hour”, Minute”, “Second” and “Station Number”. 

The Bottom_Alouette branch tried to address the station number changes via approximation. Three CSV. files were created according to the table in the document above and were organized in the following three categories: 

1.	Before 1963 (1963 included)
2.	1964 data
3.	 After  1965 (1965 included)

In case of the dot metadata, year is not included in the categories. The Bottom_Alouette branch assumes the <=1963 csv applies to dot metadata. 

 Upon further information about the information above the csv files can get uploaded in the process_directory.py document.

**Comment by emilinecsa** [comment]
Is this issue still there?
